apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2-announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-lb-pool
spec:
  blocks:
  - start: "10.0.100.200"
    stop: "10.0.100.254"